service:
  domain: http://localhost:8080/
  url-max-length: 2083

spring:
  datasource:
    #url: jdbc:h2:file:./test_db;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:testdb #JDBC URL : jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    data-password:
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: update
#  h2:
#    console:
#      enabled: true
